version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates monthly, first of the month, 8PM UTC
      interval: "monthly"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates monthly, first of the month, 8PM UTC
      interval: "monthly"
      time: "20:00"
